version: 2
jobs:
  build:
    docker:
      - image: foundationdb/foundationdb:6.0.15

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: apt-get update && apt-get install -y openjdk-8-jdk maven
      - run: bash bindings-install.sh

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn compile
